// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f47ea85e03e2c1fa688490211283d7a1)
declare namespace Cloudflare {
	interface Env {
		INDEXNOWKEY: string;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
