// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: dbbcb5c1fc850c87acb390caee963d47)
declare namespace Cloudflare {
	interface Env {
		INDEXNOWKEY: string;
		PAGE_SIZE: string;
		CHUNK_SIZE: string;
		RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
