// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2799c697a2c052804351a33ff44024b6)
declare namespace Cloudflare {
	interface Env {
		INDEXNOWKEY: SecretsStoreSecret;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
